version: '2'
services:
  network-support:
    image: leodotcloud/network-support:dev
    privileged: true
    pid: host
    labels:
      io.rancher.scheduler.global: 'true'
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/docker:/var/lib/docker
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
